CREATE TABLE Users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE Clinics (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE Specialties (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	clinic_id INT,
	FOREIGN KEY (clinic_id) REFERENCES Clinics(id)
);

CREATE TABLE Appointments (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	specialty_id INT,
	appointment_time DATETIME,
	FOREIGN KEY (user_id) REFERENCES Users(id),
	FOREIGN KEY (specialty_id) REFERENCES Specialties(id)
);